@startuml
skinparam linetype polyline
hide circle
hide stereotype
!pragma graphviz_dot jdot

skinparam class<<AS>> {
 BorderColor DarkRed
 BackgroundColor MistyRose
 HeaderBackgroundColor #f09090
}
skinparam class<<MD>> {
 BorderColor DarkSlateGray
 BackgroundColor WhiteSmoke
 HeaderBackgroundColor #909090
}
skinparam class<<FL>> {
 BorderColor #b07050
 BackgroundColor BUSINESS
 HeaderBackgroundColor #f2f295
}

skinparam class<<TM>> {
 BorderColor #505090
 BackgroundColor APPLICATION
 HeaderBackgroundColor SkyBlue
}

skinparam class<<TL>> {
 BorderColor DarkGreen
 BackgroundColor PHYSICAL
 HeaderBackgroundColor LimeGreen
}

package "Input Data" as InputData {
  package "Monthly Case Report" as MonthlyReport {
    class "**       XLS       **" as XLS<<MD>> {
        (Bulk import)
    }
    class "**    Online Forms    **" as Frms<<TL>> {
        Report
        |_ Identification
        |_ Demographics
        |_ Test Results
        |_ ARV
        |_ Co-infections
        |_ Death
        --
        }
        XLS -down[hidden]- Frms
        
  }

  
  package "Standard Data Model" as DataModel {
    class "**Standardized**\n**Report**" as StdReport<<TL>> {
        Report
        |_ Identification
        |_ Demographics  
        |_ Test Results
        |_ ARV
        |_ Co-infections
        |_ Death
        --
    }

    class "**Longitudinal**\n**Record**" as Long<<TL>> {
        Report
        |_ Identification  
        |_ Demographics  
        |_ Test Results
        |_ ARV
        |_ Co-infections
        |_ Death
        --
    }
    StdReport -down- Long
    XLS -right- StdReport: "                      "
    Frms -right- StdReport: "              "
    

  }  
/'
  package " EHR  " as EHR {
    class "**   ARV   **\n**  Data   **" as ARV<<TL>> {
    }
    Package "**  Lab  **\n**   Data   **" as LAB<<TL>> {
        class "**     VL     **\n**     Data     **" as VL<<TL>> {
        }
        class "**     CD4     **\n**     Data     **" as CD4<<TL>> {
        }
        VL -right[hidden]- CD4 : " "
        
    }
    class "**Recency**\n** Data **" as Recency<<TL>> {
    }
    class "** OTHER **\n** Data **" as OTH<<TL>> {
        Report
        |_ Identification  
        |_ Demographics  
        |_ Test Results
        |_ ARV
        |_ Co-infections
        |_ Death
        --
    }

  Recency -down- VL : " "
  ARV -right[hidden]- VL : " "
  ARV -right[hidden]- LAB : " "
  LAB -right[hidden]- OTH : " "
  
  }
'/

  'Long -down[hidden]- EHR
'  Long -down[hidden]- ARV


@enduml