@startuml
'skinparam linetype polyline
'skinparam linetype ortho
hide circle
hide stereotype
!pragma graphviz_dot smetana

skinparam class<<AS>> {
 BorderColor DarkRed
 BackgroundColor MistyRose
 HeaderBackgroundColor #f09090
}
skinparam class<<MD>> {
 BorderColor DarkSlateGray
 BackgroundColor WhiteSmoke
 HeaderBackgroundColor #909090
}
skinparam class<<FL>> {
 BorderColor #b07050
 BackgroundColor BUSINESS
 HeaderBackgroundColor #f2f295
}

skinparam class<<TM>> {
 BorderColor #505090
 BackgroundColor APPLICATION
 HeaderBackgroundColor SkyBlue
}

skinparam class<<TL>> {
 BorderColor DarkGreen
 BackgroundColor PHYSICAL
 HeaderBackgroundColor LimeGreen
}

package "HIV Case Surveillance" as HIVCaseSurveillance {
  
    class "**Standardized**\n** Case **\n**Report**" as StdReport<<TL>> {
        Report
        |_ Identification
        |_ Demographics  
        |_ Test Results
        |_ ARV
        |_ Death
          |_ Cause of Death
        --
        QuestionnaireResponse
        --
    }

    package "**  HIV Case  **\n**  Record  **" as Long<<AS>> {
       class "**Patient**" as Pat<<TM>> {
            |_ Identification     
              |_ ART ID
              |_ National ID
              |_ Passport Nr
              |_ OHRI ID
            |_ First name
            |_ Last name
            |_ Gender
            |_ Date of birth
            |_ Key population status 
            |_ Marital status
            |_ Country
            |_ State
            |_ District
            |_ City
            |_ Phone number
            |_ Guardian name
            |_ Death
              |_ Date
            --
            Patient
        }

        class "** HIV **\n** Diagnosis **" as Diag<<TM>> {
            |_ Diagnosis date  
            |_ Facility
            |_ Unique positive test ID 
            --
            Observation
        }

        class "**ARV**\n** Treatment **" as ARV<<TM>> {
            |_ Start date
            |_ End date  
            |_ ART Regimen  
            |_ Regimen line
            --
            CarePlan
        }

        class "** Recency **\n** Test **" as Rec<<TM>> {
            |_ Recency test conducted  
            |_ Test date
            |_ Result
            --
            Observation
        }

        class "** CD4 **" as CD4<<TM>> {
            |_ Test date  
            |_ Result
            |_ Percentage 
            --
            Observation
        }

        class "** Viral Load **" as VL<<TM>> {
            |_ Test date  
            |_ Result
            |_ Interpretation 
            --
            Observation
            --
        }

        class "** Cause of death **" as COD<<TM>> {
            |_ Death date  
            |_ Cause of death coded 
            |_ Cause of death other
            --
            Observation
            --
        }
    }
}  

Pat -right[hidden]- ARV : ""
ARV -right[hidden]- COD : ""
Pat -down[hidden]- Diag : ""
Diag -right[hidden]- Rec : ""
Rec -right[hidden]- VL : ""
VL -right[hidden]- CD4 : ""

caption

HIV Case Surveillance
endcaption


@enduml