@startuml
'skinparam linetype polyline
'skinparam linetype ortho
hide circle
hide stereotype
!pragma graphviz_dot smetana

skinparam class<<AS>> {
 BorderColor DarkRed
 BackgroundColor MistyRose
 HeaderBackgroundColor #f09090
}
skinparam class<<MD>> {
 BorderColor DarkSlateGray
 BackgroundColor WhiteSmoke
 HeaderBackgroundColor #909090
}
skinparam class<<FL>> {
 BorderColor #b07050
 BackgroundColor BUSINESS
 HeaderBackgroundColor #f2f295
}

skinparam class<<TM>> {
 BorderColor #505090
 BackgroundColor APPLICATION
 HeaderBackgroundColor SkyBlue
}

skinparam class<<TL>> {
 BorderColor DarkGreen
 BackgroundColor PHYSICAL
 HeaderBackgroundColor LimeGreen
}

package "HIV Case Surveillance" as HIVCaseSurveillance {


  
    class "**Standardized**\n** Case **\n**Report**" as StdReport<<TL>> {
        Report
        |_ Identification
        |_ Demographics  
        |_ Test Results
        |_ ARV
        |_ Co-infections
        |_ Death
        --
        QuestionnaireResponse
        --
    }

    package "**  HIV Case  **\n**  Record  **" as Long<<AS>> {
        class "**Patient**" as Pat<<TM>> {
            |_ Identification     
              |_ ARV
              |_ Passport
              |_ Insurance
            |_ Birth Year
            |_ Ethnicity
            |_ Name
            |_ Gender
            |_ Address
            |_ Occupation
            |_ Population
            |_ Death
              |_ Date
              |_ Cause
            --
            Patient
        }
        class "** Risk **\n** Factors **" as Risk<<TM>> {
            |_ Date Started     
            |_ Risk Factor  
            --
            Condition
        }
        class "** Pregnancy **" as Preg<<TM>> {
            |_ Date Reported
            |_ Place Reported
            |_ Delivery 
              |_ Date
              |_ Location
            |_ Outcomes
              |_ Code
              |_ Birth
                |_ Date
                |_ Gestation Age
                |_ Weight
                |_ Defects
                |_ HIV Status 
                |_ HIV Diagnosis Date  
                |_ ART start date
            --
            Condition
        }
        class "** HIV **\n** Diagnosis **" as Diag<<TM>> {
            |_ Transmission Route  
            |_ Date of Confirmation  
            |_ Confirming Lab 
            |_ Specimen 
              |_ Collection Date  
              |_ Collection Place  
            --
            Observation
        }
        class "** Recency **\n** Test **" as Rec<<TM>> {
            |_ Type (VL / Rapid)  
            |_ Date of Test  
            |_ Result
            |_ Rapid Test
              |_ Confirming Lab 
              |_ Specimen 
                |_ Collection Date  
                |_ Collection Place  
            |_ VL Test
            --
            Observation
        }
Pat -right[hidden]- Risk : ""
Risk -right[hidden]- Preg : ""
Preg -right[hidden]- Diag : ""
Diag -right[hidden]- Rec : ""

        class "**Drug**\n** Resistance **" as DRes<<TM>> {
            |_ Date of Test  
            |_ Specimen 
              |_ Collection Date  
              |_ Collection Place  
            --
            Observation
        }


        class "** CD4 **\n** Before ART **" as CD4BeforeART<<TM>> {
            |_ Date of Test  
            |_ Confirming Lab ? 
            |_ Specimen 
              |_ Collection Date  
              |_ Collection Place  
            --
            Observation
        }
        class "** CD4 **\n** During ART **" as CD4DuringART<<TM>> {
            |_ Date of Test  
            |_ Confirming Lab ? 
            |_ Specimen 
              |_ Collection Date  
              |_ Collection Place  
            --
            Observation
        }
        class "** Viral Load **\n** During ART **" as VLDuringART<<TM>> {
            |_ Date of Test  
            |_ Specimen 
              |_ Collection Date  
              |_ Collection Place  
            --
            Observation
            --
        }



        class "** Tuberculosis **\n**Prevention**" as TPT<<TM>> {
            |_ Date Started
            |_ Date Completed  
            |_ Treatment place  
            --
            CarePlan
        }
        class "** Tuberculosis **\n**Diagnosis**" as TB<<TM>> {
            |_ Diagnosis Date  
            --
            Condition
        }
        class "** Tuberculosis **\n**Treatment**" as TBT<<TM>> {
            |_ Date Started
            |_ Date Completed 
            |_ Treatment place  
            --
            CarePlan
        }
        class "**ARV**\n** Treatment **" as ARV<<TM>> {
            |_ History
            |_ Date Started
            |_ Date Stopped  
            |_ Location  
            |_ Date of LFTU
            |_ Transferred Out   
              |_ Date
              |_ Place  
            |_ 1st Line Started  
            |_ 2nd Line Started  
            |_ 3rd Line Started  
            --
            CarePlan
        }
        class "** HBV **" as HBV<<TM>> {
            |_ Diagnosis Date
            |_ Treatment
              |_ Date Started
              |_ Date Completed  
              |_ Location  
            --
            Observation
        }
        class "** HCV **" as HCV<<TM>> {
            |_ Diagnosis Date   
            |_ Treatment
              |_ Location  
            --
            Observation
        }



    }
    StdReport -down- Long: "                             "
'    Frms -right-> StdReport: "       "
'    MonthlyReport -right-> StdReport
Pat -down[hidden]- TPT : ""

TPT -right[hidden]- TB
TB -right[hidden]- TBT
TBT -right[hidden]- HBV : ""
HBV -right[hidden]- HCV : ""


TPT -down[hidden]- ARV : ""

ARV -right[hidden]- DRes : ""
DRes -right[hidden]- CD4BeforeART : ""
CD4BeforeART -right[hidden]- CD4DuringART : ""
CD4DuringART -right[hidden]- VLDuringART : ""
DRes -right[hidden]- CD4BeforeART : ""

  }  
'MonthlyReport -right[hidden]-> StdReport

  
caption

HIV Case Surveillance
endcaption


@enduml