@startuml
'skinparam linetype polyline
'skinparam linetype ortho
hide circle
hide stereotype
!pragma graphviz_dot smatana

skinparam class<<AS>> {
 BorderColor DarkRed
 BackgroundColor MistyRose
 HeaderBackgroundColor #f09090
}
skinparam class<<MD>> {
 BorderColor DarkSlateGray
 BackgroundColor WhiteSmoke
 HeaderBackgroundColor #909090
}
skinparam class<<FL>> {
 BorderColor #b07050
 BackgroundColor BUSINESS
 HeaderBackgroundColor #f2f295
}

skinparam class<<TM>> {
 BorderColor #505090
 BackgroundColor APPLICATION
 HeaderBackgroundColor SkyBlue
}

skinparam class<<TL>> {
 BorderColor DarkGreen
 BackgroundColor PHYSICAL
 HeaderBackgroundColor LimeGreen
}

package "HIV Case Surveillance" as HIVCaseSurveillance {
  package "Monthly Case Report" as MonthlyReport {
    class "**       XLS       **" as XLS<<MD>> {
        (Bulk import)
    }
    class "**    Online Forms    **" as Frms<<TL>> {
        Report
        |_ Identification
        |_ Demographics
        |_ Test Results
        |_ ARV
        |_ Co-infections
        |_ Death
        --
        QuestionnaireResponse
        }
'        XLS .down.> Frms
        XLS ..> Frms
  }

  
  package "Standard Data Layer" as DataModel {
    class "**Standardized**\n** Case **\n**Report**" as StdReport<<TL>> {
        Report
        |_ Identification
        |_ Demographics  
        |_ Test Results
        |_ ARV
        |_ Co-infections
        |_ Death
        --
        
    }

    class "**Longitudinal**\n**Record**" as Long<<TL>> {
        Report
        |_ Identification  
        |_ Demographics  
        |_ Test Results
        |_ ARV
        |_ Co-infections
        |_ Death
        --
    }
    StdReport -down- Long: "                             "
    'XLS -right- StdReport: "                                                                                    "
    XLS -> StdReport
    Frms -right-> StdReport: "       "
    

  }  

  package "   EHR    " as EHR {
    class "**     ARV     **\n**  Data   **" as ARV<<TL>> {
     --
     MedicationUsage
     }
    Package "**  Lab  **\n**   Data   **" as LAB<<TL>> {
        class "**     VL     **\n**     Data     **" as VL<<TL>> {
      --
      Observation
        }
        class "**       CD4       **\n**     Data     **" as CD4<<TL>> {
      --
      Observation
        }
        VL -right[hidden]- CD4 : "              "
    }
  'CD4 -left[hidden]- ARV : " "

    class "**    Recency     **\n** Data **" as Recency<<TL>> {
      --
      Observation
    }

    class "**    Other    **\n** Data **" as OTH<<TL>> {
'        Report
'        |_ Identification  
'        |_ Demographics  
'        |_ Test Results
'        |_ ARV
'        |_ Co-infections
'        |_ Death
        --
        ...
    }

  Recency <-down- LAB : "  "
  ARV -up[hidden]- VL : " "
'  LAB -right[hidden]- OTH : " "
'Recency -right[hidden]- Frms : " "
ARV -right[hidden]- OTH : " "
CD4 -down[hidden]- OTH : " "
OTH -right[hidden]- Long : " "
  
  }
 
  'Long -down[hidden]- EHR
  Frms -down[hidden]- EHR
 EHR -> Frms :"                  "
 EHR ..> Long
'  EHR -right[hidden]- DataModel
  EHR -right[hidden]- DataModel : "                     "
  
caption
HIV Case Surveillance
endcaption


@enduml