@startuml
'skinparam linetype polyline
'skinparam linetype ortho
hide circle
hide stereotype
!pragma graphviz_dot smetana

skinparam class<<AS>> {
 BorderColor DarkRed
 BackgroundColor MistyRose
 HeaderBackgroundColor #f09090
}
skinparam class<<MD>> {
 BorderColor DarkSlateGray
 BackgroundColor WhiteSmoke
 HeaderBackgroundColor #909090
}
skinparam class<<FL>> {
 BorderColor #b07050
 BackgroundColor BUSINESS
 HeaderBackgroundColor #f2f295
}

skinparam class<<TM>> {
 BorderColor #505090
 BackgroundColor APPLICATION
 HeaderBackgroundColor SkyBlue
}

skinparam class<<TL>> {
 BorderColor DarkGreen
 BackgroundColor PHYSICAL
 HeaderBackgroundColor LimeGreen
}

package "HIV Case Surveillance" as HIVCaseSurveillance {
  package "Monthly Case Report" as MonthlyReport {
    class "**    Online Forms    **" as Frms<<TL>> {
        Report
        |_ Identification
        |_ Demographics
        |_ Test Results
        |_ ARV
        |_ Co-infections
        |_ Death
        --
        QuestionnaireResponse
        }
  }

  
    class "**Standardized**\n** Case **\n**Report**" as StdReport<<TL>> {
        Report
        |_ Identification
        |_ Demographics  
        |_ Test Results
        |_ ARV
        |_ Co-infections
        |_ Death
        --
        QuestionnaireResponse
        --
    }

    package "**  Longitudinal  **\n**  Record  **" as Long<<TL>> {
        class "**Patient**" as Patient<<TL>> {
            Report
            |_ Identification
            |_ Demographics  
            |_ Test Results
            |_ ARV
            |_ Co-infections
            |_ Death
            --
            Patient
            --
        }
        class "**ARV**\n** Treatment **" as ARV<<TL>> {
            Report
            |_ Identification
            --
            CarePlan
            --
        }

        class "**Drug**\n** Resistance **" as DRes<<TL>> {
            Report
            |_ Identification
            --
            Observation
            --
        }

        class "** Recency **\n** Test **" as Rec<<TL>> {
            Report
            |_ Identification
            --
            Observation
            --
        }
        class "** Risk **\n** Factors **" as Risk<<TL>> {
            Report
            |_ Identification
            --
            Condition
            --
        }
        class "** HIV **\n** Diagnosis **" as Diag<<TL>> {
            Report
            |_ Identification
            --
            Observation
            --
        }

        class "** CD4 **\n** BeforeART **" as CD4BeforeART<<TL>> {
            Report
            |_ Identification
            --
            Observation
            --
        }
        class "** CD4 **\n** DuringART **" as CD4DuringART<<TL>> {
            Report
            |_ Identification
            --
            Observation
            --
        }
        class "** VL **\n** DuringART **" as VLDuringART<<TL>> {
            Report
            |_ Identification
            --
            Observation
            --
        }
        class "** Tuberculosis **" as TB<<TL>> {
            Report
            |_ Identification
            --
            Observation
            --
        }
        class "** Tuberculosis **\n**Treatment**" as TBT<<TL>> {
            Report
            |_ Identification
            --
            Observation
            --
        }
        class "** Tuberculosis **\n**Prevention**" as TPT<<TL>> {
            Report
            |_ Identification
            --
            Observation
            --
        }



    }
    StdReport -down- Long: "                             "
    Frms -right-> StdReport: "       "

MonthlyReport -right-> StdReport

  }  
MonthlyReport -right[hidden]-> StdReport

  
caption
HIV Case Surveillance
endcaption


@enduml